name: grupo-3
services:
  database-prod:
    image: 'mysql:${VERSION_MYSQL}'
    container_name: database-prod
    volumes:
      - ./db/data_prod:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - '3312:${DB_PORT}'

  flyway:
    image: 'flyway/flyway:${VERSION_FLYWAY}'
    volumes:
      - ./sql:/flyway/sql
    command:
      - '-url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false'
      - '-user=${DB_USERNAME}'
      - '-password=${DB_PASSWORD}'
      - '-connectRetries=60'
      - 'migrate'

  backend-prod:
    image: muinidoconeg/cotiledonapp:2.0.0-test
    depends_on:
      - database-prod
    environment:
      - PORT=${API_PORT}
      - AMBIENTE=${AMBIENTE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - RUTA_ESTATICOS=${RUTA_ESTATICOS}
      - RUTA_FISICA=${RUTA_FISICA}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8080:${API_PORT}"

  frontend-prod:
    build:
      context: .
      args:
        - VITE_URL_ENDPOINT_BACKEND=${VITE_URL_ENDPOINT_BACKEND}
        - VITE_API_URL=${VITE_API_URL}
    container_name: frontend
    depends_on:
      - backend-prod
    ports:
      - "3000:80"

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - backend-prod
      - frontend-prod
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html