version: '3.8'
services:
  database-prod:
    image: mysql:8.0
    container_name: database-prod
    volumes:
      - ./db/data_prod:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=clave123
      - MYSQL_DATABASE=plantai_db
    ports:
      - "3312:3306"

  flyway:
    image: flyway/flyway:10.20.1-alpine
    volumes:
      - ./sql:/flyway/sql
    command: -url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE} -user=${DB_USERNAME} -password=${DB_PASSWORD} -connectRetries=60 migrate
    environment:
      - DB_HOST=database-prod
      - DB_PORT=3306
      - DB_DATABASE=plantai_db
      - DB_USERNAME=root
      - DB_PASSWORD=clave123

  cotiledon-prod:
    image: nicolasf1/cotiledonapp:1.9.1
    depends_on:
      - database-prod
    environment:
      - AMBIENTE=production
      - DB_HOST=database-prod
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=clave123
      - DB_DATABASE=plantai_db
    ports:
      - "8080:8080"

  frontend-prod:
    image: plantaifinalvers:1
    depends_on:
      - cotiledon-prod
    ports:
      - "5173:80"
    env_file:
      - .env.production
